df <- read.csv('q1.csv', header = F)
df <- as.matrix(df)
plot(x = df[1,], y = df[2,], type = 'l', col = "dodgerblue3", xlab = 'Volatility', ylab = 'Price', main = 'Fixed-Strike Lookback Call')
plot(x = df[1,], y = df[3,], type = 'l', col = "dodgerblue3", xlab = 'Volatility', ylab = 'Price', main = 'Fixed-Strike Lookback Put')

time <- c(3:8)
lambda1_val <- as.matrix(read.csv('lambda1_val.csv',header = F))
lambda1_et <- as.matrix(read.csv('lambda1_et.csv',header = F))
lambda1_prob <- as.matrix(read.csv('lambda1_prob.csv',header = F))

par(mfrow=c(2,3))
plot(main = 'lambda1 = 0.2', ylab = 'Value of Option',x = time, y = lambda1_val[1,], type = 'l', ylim = c(min(lambda1_val),max(lambda1_val)))
lines(x = time, y = lambda1_val[2,], col = 'blue')
lines(x = time, y = lambda1_val[3,], col = 'orange')
lines(x = time, y = lambda1_val[4,], col = 'red')
lines(x = time, y = lambda1_val[5,], col = 'purple')
lines(x = time, y = lambda1_val[6,], col = 'green')
lines(x = time, y = lambda1_val[7,], col = 'brown')
lines(x = time, y = lambda1_val[8,], col = 'pink')
lines(x = time, y = lambda1_val[9,], col = 'grey')

plot(main = 'lambda1 = 0.2', ylab = 'Exercise Time',x = time, y = lambda1_et[1,], type = 'l', ylim = c(min(lambda1_et),max(lambda1_et)))
lines(x = time, y = lambda1_et[2,], col = 'blue')
lines(x = time, y = lambda1_et[3,], col = 'orange')
lines(x = time, y = lambda1_et[4,], col = 'red')
lines(x = time, y = lambda1_et[5,], col = 'purple')
lines(x = time, y = lambda1_et[6,], col = 'green')
lines(x = time, y = lambda1_et[7,], col = 'brown')
lines(x = time, y = lambda1_et[8,], col = 'pink')
lines(x = time, y = lambda1_et[9,], col = 'grey')

plot(main = 'lambda1 = 0.2', ylab = 'Default Probability',x = time, y = lambda1_prob[1,], type = 'l', ylim = c(min(lambda1_prob),max(lambda1_prob)))
lines(x = time, y = lambda1_prob[2,], col = 'blue')
lines(x = time, y = lambda1_prob[3,], col = 'orange')
lines(x = time, y = lambda1_prob[4,], col = 'red')
lines(x = time, y = lambda1_prob[5,], col = 'purple')
lines(x = time, y = lambda1_prob[6,], col = 'green')
lines(x = time, y = lambda1_prob[7,], col = 'brown')
lines(x = time, y = lambda1_prob[8,], col = 'pink')
lines(x = time, y = lambda1_prob[9,], col = 'grey')

lambda2_val <- as.matrix(read.csv('lambda2_val.csv',header = F))
lambda2_et <- as.matrix(read.csv('lambda2_et.csv',header = F))
lambda2_prob <- as.matrix(read.csv('lambda2_prob.csv',header = F))

plot(main = 'lambda2 = 0.4', ylab = 'Value of Option',x = time, y = lambda2_val[1,], type = 'l', ylim = c(min(lambda2_val),max(lambda2_val)))
lines(x = time, y = lambda2_val[2,], col = 'blue')
lines(x = time, y = lambda2_val[3,], col = 'orange')
lines(x = time, y = lambda2_val[4,], col = 'red')
lines(x = time, y = lambda2_val[5,], col = 'purple')
lines(x = time, y = lambda2_val[6,], col = 'green')
lines(x = time, y = lambda2_val[7,], col = 'brown')
lines(x = time, y = lambda2_val[8,], col = 'pink')

plot(main = 'lambda2 = 0.4', ylab = 'Exercise Time', x = time, y = lambda2_et[1,], type = 'l', ylim = c(min(lambda2_et),max(lambda2_et)))
lines(x = time, y = lambda2_et[2,], col = 'blue')
lines(x = time, y = lambda2_et[3,], col = 'orange')
lines(x = time, y = lambda2_et[4,], col = 'red')
lines(x = time, y = lambda2_et[5,], col = 'purple')
lines(x = time, y = lambda2_et[6,], col = 'green')
lines(x = time, y = lambda2_et[7,], col = 'brown')
lines(x = time, y = lambda2_et[8,], col = 'pink')

plot(main = 'lambda2 = 0.4', ylab = 'Default Probability',x = time, y = lambda2_prob[1,], type = 'l', ylim = c(min(lambda2_prob),max(lambda2_prob)))
lines(x = time, y = lambda2_prob[2,], col = 'blue')
lines(x = time, y = lambda2_prob[3,], col = 'orange')
lines(x = time, y = lambda2_prob[4,], col = 'red')
lines(x = time, y = lambda2_prob[5,], col = 'purple')
lines(x = time, y = lambda2_prob[6,], col = 'green')
lines(x = time, y = lambda2_prob[7,], col = 'brown')
lines(x = time, y = lambda2_prob[8,], col = 'pink')

