s_range <- seq(4,16,0.25)
calls <- read.csv('calls.csv', header = F)
calls <- as.data.frame(calls)
plot(x = s_range, calls[1,], type = 'l', main = 'Call', xlab = 'Option Price', ylab = 'Current Stock Price')
lines(x = s_range, calls[2,], col = 'dodgerblue3')
lines(x = s_range, calls[3,], col = 'firebrick')
plot(x = s_range, calls[1,], type = 'l', xlim = c(9.98,10.02), ylim = c(0.65,0.67),main = 'Call, Zoomed In', xlab = 'Option Price', ylab = 'Current Stock Price')
lines(x = s_range, calls[2,], col = 'dodgerblue3')
lines(x = s_range, calls[3,], col = 'firebrick')

puts <- read.csv('puts.csv', header = F)
puts <- as.data.frame(puts)
plot(x = s_range, puts[1,], type = 'l',main = 'Put', xlab = 'Option Price', ylab = 'Current Stock Price')
lines(x = s_range, puts[2,], col = 'dodgerblue3')
lines(x = s_range, puts[3,], col = 'firebrick')
plot(x = s_range, puts[1,], type = 'l', xlim = c(9.98,10.02), ylim = c(0.46,0.5),main = 'Put, Zoomed In', xlab = 'Option Price', ylab = 'Current Stock Price')
lines(x = s_range, puts[2,], col = 'dodgerblue3')
lines(x = s_range, puts[3,], col = 'firebrick')
