kappa <- read.csv("kappa.csv", header = F)
kappa <- as.matrix(kappa)
plot(x = kappa[1,], y = kappa[2,], type = 'l')
rbar <- read.csv("rbar.csv", header = F)
rbar <- as.matrix(rbar)
plot(x = rbar[1,], y = rbar[2,], type = 'l')
sigma <- read.csv("sigma.csv", header = F)
sigma <- as.matrix(sigma)
plot(x = sigma[1,], y = sigma[2,], type = 'l')
