kappa <- read.csv("kappa.csv", header = F)
kappa <- as.matrix(kappa)
plot(x = kappa[1,], y = kappa[2,], type = 'l', main = 'Price vs. Kappa', xlab = 'Kappa', ylab = 'Price')
rbar <- read.csv("rbar.csv", header = F)
rbar <- as.matrix(rbar)
plot(x = rbar[1,], y = rbar[2,], type = 'l', main = 'Price vs. R Bar', xlab = 'R Bar', ylab = 'Price')
sigma <- read.csv("sigma.csv", header = F)
sigma <- as.matrix(sigma)
plot(x = sigma[1,], y = sigma[2,], type = 'l', main = 'Price vs. Sigma', xlab = 'Sigma', ylab = 'Price')
