greeks <- read.csv('greeks.csv', header = F)
greeks <- as.matrix(t(greeks))
colnames(greeks) <- c('Delta','Vega','Theta','Rho','Gamma');
rownames(greeks) <- c(15:25)
plot(x = c(15:25), y = greeks[,1], type = 'l', col = 'dodgerblue3', main = 'Delta', xlab = 'Stock Price @ t = 0', ylab = 'Value')
plot(x = c(15:25), y = greeks[,2], type = 'l', col = 'dodgerblue3', main = 'Vega', xlab = 'Stock Price @ t = 0', ylab = 'Value')
plot(x = c(15:25), y = greeks[,3], type = 'l', col = 'dodgerblue3', main = 'Theta', xlab = 'Stock Price @ t = 0', ylab = 'Value')
plot(x = c(15:25), y = greeks[,4], type = 'l', col = 'dodgerblue3', main = 'Rho', xlab = 'Stock Price @ t = 0', ylab = 'Value')
plot(x = c(15:25), y = greeks[,5], type = 'l', col = 'dodgerblue3', main = 'Gamma', xlab = 'Stock Price @ t = 0', ylab = 'Value')
halton <- read.csv('halton.csv', header = F)
halton <- as.matrix(t(halton))
colnames(halton) <- c('U1','U2','Base 2', 'Base 7', 'Base 4')
plot(x = halton[,1], y = halton[,2], pch = 20, col = 'green3', main = 'U[0,1], H(2,7), H(2,4)', xlab = 'x', ylab = 'y')
points(x = halton[,3], y = halton[,4], pch = 20, col = 'firebrick')
points(x = halton[,3], y = halton[,5], pch = 20, col = 'dodgerblue3')
